version: "3.5"
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.84.0
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - /opt/victoriametricsdata/lib/victoriametrics:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    restart: always
    network_mode: "host"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana-data:/var/lib/grafana
    network_mode: "host"
    restart: always
    user: root